# Generated by Django 3.2.5 on 2021-08-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('address', models.CharField(default='N/A', max_length=100)),
                ('phone', models.CharField(default='N/A', max_length=30)),
                ('email', models.CharField(default='None', max_length=40)),
                ('emergency_contacts', models.CharField(default='N/A', max_length=100)),
                ('preferred_language', models.CharField(default='N/A', max_length=100)),
                ('additional_notes', models.TextField(default='N/A')),
                ('vaccinated', models.BooleanField(default=None)),
                ('notify_email', models.BooleanField(default=None)),
                ('notify_text', models.BooleanField(default=None)),
                ('notify_call', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('phone', models.CharField(default='N/A', max_length=30)),
                ('email', models.CharField(default='None', max_length=40)),
                ('dob', models.CharField(default='N/A', max_length=10)),
                ('vaccinated', models.BooleanField(default=None)),
                ('notify_email', models.BooleanField(default=None)),
                ('notify_text', models.BooleanField(default=None)),
                ('notify_call', models.BooleanField(default=None)),
                ('availability', models.JSONField(default=dict)),
                ('current_appointments', models.JSONField(default=dict, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('purpose_of_trip', models.TextField(default='N/A')),
                ('notes', models.TextField(default='N/A')),
                ('senior', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.senior')),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.volunteer')),
            ],
        ),
    ]
