# Generated by Django 3.2.5 on 2021-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='senior',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='senior',
            name='vaccination_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='senior',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='senior',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
