# Generated by Django 3.2.5 on 2021-08-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='additional_notes',
            field=models.TextField(default='N/A'),
        ),
    ]
