# Generated by Django 3.2.5 on 2021-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='additional_notes',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_and_time',
            field=models.CharField(max_length=50),
        ),
    ]
