# Generated by Django 3.2.5 on 2021-09-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose_of_trip',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
