# Generated by Django 3.2.5 on 2021-09-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='current_appointments',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='surveystatus',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
