# Generated by Django 3.2.5 on 2021-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveystatus',
            old_name='survey_id',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='day',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='current_appointments',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='surveystatus',
            name='date_sent',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose_of_trip',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='additional_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='emergency_contacts',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='notify_call',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='preferred_language',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='senior',
            name='vaccinated',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='minor',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='vaccinated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
