# Generated by Django 3.2.5 on 2021-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0002_auto_20210729_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senior',
            old_name='vaccination_status',
            new_name='vaccinated',
        ),
        migrations.AlterField(
            model_name='senior',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
