# Generated by Django 3.2.5 on 2021-08-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0002_auto_20210812_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='galaxy_id',
            field=models.IntegerField(default=None),
        ),
    ]
