# Generated by Django 3.2.5 on 2021-07-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0003_auto_20210729_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior',
            name='notes',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
