# Generated by Django 3.2.5 on 2021-08-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0003_volunteer_galaxy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='galaxy_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
