# Generated by Django 3.2.5 on 2021-08-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0004_alter_volunteer_galaxy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notify_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='notify_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
    ]
