# Generated by Django 3.2.5 on 2021-07-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0004_senior_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior',
            name='notes',
        ),
    ]
