# Generated by Django 3.2.5 on 2021-07-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0004_senior_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='N/A')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='senior',
            name='notes',
        ),
    ]
