# Generated by Django 3.2.5 on 2021-07-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0005_auto_20210730_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='senior',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.senior'),
        ),
    ]
