# Generated by Django 3.2.5 on 2021-08-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0005_auto_20210817_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='additional_notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
