# Generated by Django 3.2.5 on 2021-07-31 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0006_appointment_senior'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='date_and_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose_of_trip',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='senior',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.senior'),
        ),
    ]
