# Generated by Django 3.2.5 on 2021-08-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0006_alter_volunteer_additional_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_9_10', models.BooleanField(default=False)),
                ('_10_11', models.BooleanField(default=False)),
                ('_11_12', models.BooleanField(default=False)),
                ('_12_1', models.BooleanField(default=False)),
                ('_1_2', models.BooleanField(default=False)),
                ('all', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_14', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_16', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_17', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_18', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_19', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_20', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_23', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_24', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_25', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_26', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_27', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_28', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_29', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_30', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_31', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
                ('_9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduling_application.day')),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.availability'),
        ),
    ]
