# Generated by Django 3.2.5 on 2021-08-01 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0009_appointment_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.volunteer'),
        ),
    ]
