# Generated by Django 3.2.5 on 2021-08-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0009_auto_20210825_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='survey_token',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
