# Generated by Django 3.2.5 on 2021-08-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0010_volunteer_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='survey_token',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
