# Generated by Django 3.2.5 on 2021-08-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0010_alter_appointment_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='day',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
