# Generated by Django 3.2.5 on 2021-08-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0011_volunteer_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.CharField(default='None', max_length=40),
        ),
    ]
