# Generated by Django 3.2.5 on 2021-08-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0011_alter_volunteer_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='survey_token',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
