# Generated by Django 3.2.5 on 2021-09-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0012_alter_volunteer_survey_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='scheduling_application.volunteer'),
        ),
    ]
