# Generated by Django 3.2.5 on 2021-08-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0012_volunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
