# Generated by Django 3.2.5 on 2021-08-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0013_volunteer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.volunteer'),
        ),
        migrations.AlterField(
            model_name='senior',
            name='address',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
