# Generated by Django 3.2.5 on 2021-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0013_alter_appointment_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='volunteer',
            field=models.ManyToManyField(related_name='Appointments', to='scheduling_application.Volunteer'),
        ),
    ]
