# Generated by Django 3.2.5 on 2021-08-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0013_volunteer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior',
            name='age',
        ),
        migrations.AddField(
            model_name='senior',
            name='additional_notes',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='senior',
            name='call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senior',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senior',
            name='emergency_contacts',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='senior',
            name='language',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='senior',
            name='phone',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='senior',
            name='text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='senior',
            name='address',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
