# Generated by Django 3.2.5 on 2021-09-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0014_auto_20210902_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
