# Generated by Django 3.2.5 on 2021-08-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0014_auto_20210806_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senior',
            old_name='language',
            new_name='preferred_language',
        ),
    ]
