# Generated by Django 3.2.5 on 2021-09-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0012_surveystatus'),
        ('scheduling_application', '0015_volunteer_address'),
    ]

    operations = [
    ]
