# Generated by Django 3.2.5 on 2021-08-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0015_auto_20210809_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='notif_call',
            new_name='notify_call',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='notif_email',
            new_name='notify_email',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='notif_test',
            new_name='notify_text',
        ),
    ]
