# Generated by Django 3.2.5 on 2021-08-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0016_volunteer_current_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='day',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='day_time',
            field=models.CharField(default='M 9:00-17:00', max_length=100),
        ),
    ]
