# Generated by Django 3.2.5 on 2021-09-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0016_merge_0012_surveystatus_0015_volunteer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appointments', to='scheduling_application.volunteer'),
        ),
    ]
