# Generated by Django 3.2.5 on 2021-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0017_auto_20210904_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='minor',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
