# Generated by Django 3.2.5 on 2021-08-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0017_auto_20210807_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senior',
            old_name='call',
            new_name='notify_call',
        ),
        migrations.RenameField(
            model_name='senior',
            old_name='text',
            new_name='notify_email',
        ),
        migrations.AddField(
            model_name='senior',
            name='availability',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='senior',
            name='notify_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='notify_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='notify_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='senior',
            name='email',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='current_appointments',
            field=models.TextField(default='M', editable=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='day_time',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
