# Generated by Django 3.2.5 on 2021-08-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0018_auto_20210809_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior',
            name='availability',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.JSONField(default={}),
        ),
    ]
