# Generated by Django 3.2.5 on 2021-09-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0018_volunteer_minor'),
        ('scheduling_application', '0018_volunteer_unsubscribed'),
    ]

    operations = [
    ]
