# Generated by Django 3.2.5 on 2021-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0019_merge_20210907_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
