# Generated by Django 3.2.5 on 2021-08-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0019_auto_20210809_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.JSONField(default=dict),
        ),
    ]
