# Generated by Django 3.2.5 on 2021-08-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0020_alter_volunteer_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(default='None', max_length=50)),
                ('tue', models.CharField(default='None', max_length=50)),
                ('wed', models.CharField(default='None', max_length=50)),
                ('thu', models.CharField(default='None', max_length=50)),
                ('fri', models.CharField(default='None', max_length=50)),
                ('sat', models.CharField(default='None', max_length=50)),
                ('sun', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='senior',
            name='availability',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.availability'),
        ),
    ]
