# Generated by Django 3.2.5 on 2021-08-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0021_auto_20210809_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_application.availability'),
        ),
    ]
