# Generated by Django 3.2.5 on 2021-08-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0022_alter_senior_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior',
            name='availability',
        ),
    ]
