# Generated by Django 3.2.5 on 2021-08-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0024_senior_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senior',
            name='availability',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='current_appointments',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
