# Generated by Django 3.2.5 on 2021-08-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0026_remove_volunteer_day_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='dob',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
