# Generated by Django 3.2.5 on 2021-08-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0027_volunteer_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='age',
        ),
    ]
