# Generated by Django 3.2.5 on 2021-08-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_application', '0016_auto_20210810_1410'),
        ('scheduling_application', '0028_remove_volunteer_age'),
    ]

    operations = [
    ]
